export const AdManager = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_tokenAddress",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "VideoId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "AdId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "Reward",
        type: "uint256",
      },
    ],
    name: "AdDisplayed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "AdId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "MaxBudget",
        type: "uint256",
      },
    ],
    name: "CampaignStarted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "AdId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "RemainingBudget",
        type: "uint256",
      },
    ],
    name: "CampaignStopped",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "RoomId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "AdId",
        type: "uint256",
      },
    ],
    name: "PublisherRoomAdded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "RoomId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "AdId",
        type: "uint256",
      },
    ],
    name: "PublisherRoomRemoved",
    type: "event",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_AdId", type: "uint256" },
      { internalType: "uint256", name: "_RoomId", type: "uint256" },
    ],
    name: "addPublishingRoom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_videoId", type: "uint256" },
      { internalType: "uint256", name: "_AdId", type: "uint256" },
    ],
    name: "displayAd",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_adId", type: "uint256" }],
    name: "getAd",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "Id", type: "uint256" },
          { internalType: "string", name: "URI", type: "string" },
          {
            internalType: "address",
            name: "Advertiser",
            type: "address",
          },
          {
            internalType: "uint256[]",
            name: "PublishingRooms",
            type: "uint256[]",
          },
          { internalType: "bool", name: "Active", type: "bool" },
          {
            internalType: "uint256",
            name: "TotalSpent",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "CurrentBudget",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "MaxBudget",
            type: "uint256",
          },
        ],
        internalType: "struct ITokens.Ad",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_id", type: "uint256" }],
    name: "getVideo",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "Id", type: "uint256" },
          { internalType: "string", name: "URI", type: "string" },
          { internalType: "address", name: "Owner", type: "address" },
          { internalType: "address", name: "Creator", type: "address" },
          { internalType: "uint256", name: "Price", type: "uint256" },
          {
            internalType: "uint256",
            name: "SocialTokenId",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "OwnerPercentage",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "HoldersPercentage",
            type: "uint256",
          },
          {
            internalType: "address[]",
            name: "Benefeciaries",
            type: "address[]",
          },
          { internalType: "bool", name: "Listed", type: "bool" },
          { internalType: "bool", name: "Published", type: "bool" },
          { internalType: "bool", name: "AdsEnabled", type: "bool" },
          { internalType: "uint256", name: "RoomId", type: "uint256" },
        ],
        internalType: "struct ITokens.Video",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "", type: "address" },
      { internalType: "address", name: "", type: "address" },
      { internalType: "uint256[]", name: "", type: "uint256[]" },
      { internalType: "uint256[]", name: "", type: "uint256[]" },
      { internalType: "bytes", name: "", type: "bytes" },
    ],
    name: "onERC1155BatchReceived",
    outputs: [{ internalType: "bytes4", name: "", type: "bytes4" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "", type: "address" },
      { internalType: "address", name: "", type: "address" },
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "bytes", name: "", type: "bytes" },
    ],
    name: "onERC1155Received",
    outputs: [{ internalType: "bytes4", name: "", type: "bytes4" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_AdId", type: "uint256" },
      { internalType: "uint256", name: "_RoomId", type: "uint256" },
    ],
    name: "removePublishingRoom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_AdId", type: "uint256" },
      { internalType: "uint256", name: "_maxBudget", type: "uint256" },
    ],
    name: "startCampaign",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_AdId", type: "uint256" }],
    name: "stopCampaign",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes4", name: "interfaceId", type: "bytes4" }],
    name: "supportsInterface",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
];
export const ContentManager = [
  {
    inputs: [{ internalType: "address", name: "_tokens", type: "address" }],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "creator",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "price",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "videoIds",
        type: "uint256",
      },
    ],
    name: "SocialTokenLaunched",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "videoId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "roomId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "creator",
        type: "address",
      },
      {
        indexed: false,
        internalType: "string",
        name: "URI",
        type: "string",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "adsEnabled",
        type: "bool",
      },
    ],
    name: "VideoPublished",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "videoId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "roomId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "owner",
        type: "address",
      },
    ],
    name: "VideoUnpublished",
    type: "event",
  },
  {
    inputs: [{ internalType: "uint256", name: "_id", type: "uint256" }],
    name: "launchSocialToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_id", type: "uint256" },
      {
        internalType: "uint256",
        name: "_ownerPercentage",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_holdersPercentage",
        type: "uint256",
      },
      { internalType: "bool", name: "_adsEnabled", type: "bool" },
    ],
    name: "publishVideo",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_id", type: "uint256" }],
    name: "unpublishVideo",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
export const Marketplace = [
  {
    inputs: [{ internalType: "address", name: "_token", type: "address" }],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "_id",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "_price",
        type: "uint256",
      },
    ],
    name: "RoomListed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "_id",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "_buyer",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "_seller",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "_price",
        type: "uint256",
      },
    ],
    name: "RoomPurchased",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "_id",
        type: "uint256",
      },
    ],
    name: "RoomUnlisted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "_id",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "_price",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "_seller",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "SocialTokenListed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "_id",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "_buyer",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "_seller",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "_price",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "SocialTokenPurchased",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "_id",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "_seller",
        type: "address",
      },
    ],
    name: "SocialTokenUnlisted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "_id",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "_price",
        type: "uint256",
      },
    ],
    name: "VideoListed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "_id",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "_buyer",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "_seller",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "_price",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "_roomId",
        type: "uint256",
      },
    ],
    name: "VideoPurchased",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "_id",
        type: "uint256",
      },
    ],
    name: "VideoUnlisted",
    type: "event",
  },
  {
    inputs: [{ internalType: "uint256", name: "_id", type: "uint256" }],
    name: "buyRoom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_id", type: "uint256" },
      { internalType: "uint256", name: "_amount", type: "uint256" },
      { internalType: "address", name: "_seller", type: "address" },
    ],
    name: "buySocialToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_id", type: "uint256" },
      { internalType: "uint256", name: "_roomId", type: "uint256" },
    ],
    name: "buyVideo",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_id", type: "uint256" }],
    name: "getRoom",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "Id", type: "uint256" },
          { internalType: "string", name: "URI", type: "string" },
          { internalType: "address", name: "Creator", type: "address" },
          { internalType: "address", name: "Owner", type: "address" },
          { internalType: "uint256", name: "Price", type: "uint256" },
          {
            internalType: "uint256",
            name: "DisplayReward",
            type: "uint256",
          },
          {
            internalType: "uint256[]",
            name: "VideoIds",
            type: "uint256[]",
          },
          { internalType: "bool", name: "Listed", type: "bool" },
        ],
        internalType: "struct ITokens.Room",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_id", type: "uint256" }],
    name: "getSocialToken",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "ID", type: "uint256" },
          { internalType: "string", name: "URI", type: "string" },
          {
            internalType: "uint256",
            name: "totalSupply",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "circulatingSupply",
            type: "uint256",
          },
          { internalType: "uint256", name: "price", type: "uint256" },
          { internalType: "bool", name: "launched", type: "bool" },
          { internalType: "address", name: "creator", type: "address" },
          {
            internalType: "uint256",
            name: "maxHoldingAmount",
            type: "uint256",
          },
          { internalType: "uint256", name: "videoIds", type: "uint256" },
        ],
        internalType: "struct ITokens.SocialToken",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_id", type: "uint256" }],
    name: "getVideo",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "Id", type: "uint256" },
          { internalType: "string", name: "URI", type: "string" },
          { internalType: "address", name: "Owner", type: "address" },
          { internalType: "address", name: "Creator", type: "address" },
          { internalType: "uint256", name: "Price", type: "uint256" },
          {
            internalType: "uint256",
            name: "SocialTokenId",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "OwnerPercentage",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "HoldersPercentage",
            type: "uint256",
          },
          {
            internalType: "address[]",
            name: "Benefeciaries",
            type: "address[]",
          },
          { internalType: "bool", name: "Listed", type: "bool" },
          { internalType: "bool", name: "Published", type: "bool" },
          { internalType: "bool", name: "AdsEnabled", type: "bool" },
          { internalType: "uint256", name: "RoomId", type: "uint256" },
        ],
        internalType: "struct ITokens.Video",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_id", type: "uint256" },
      { internalType: "uint256", name: "_price", type: "uint256" },
    ],
    name: "listRoom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_id", type: "uint256" },
      { internalType: "uint256", name: "_amount", type: "uint256" },
      { internalType: "uint256", name: "_price", type: "uint256" },
    ],
    name: "listSocialToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_id", type: "uint256" },
      { internalType: "uint256", name: "_price", type: "uint256" },
    ],
    name: "listVideo",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "", type: "address" },
      { internalType: "address", name: "", type: "address" },
      { internalType: "uint256[]", name: "", type: "uint256[]" },
      { internalType: "uint256[]", name: "", type: "uint256[]" },
      { internalType: "bytes", name: "", type: "bytes" },
    ],
    name: "onERC1155BatchReceived",
    outputs: [{ internalType: "bytes4", name: "", type: "bytes4" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "", type: "address" },
      { internalType: "address", name: "", type: "address" },
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "bytes", name: "", type: "bytes" },
    ],
    name: "onERC1155Received",
    outputs: [{ internalType: "bytes4", name: "", type: "bytes4" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes4", name: "interfaceId", type: "bytes4" }],
    name: "supportsInterface",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_id", type: "uint256" }],
    name: "unListRoom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_id", type: "uint256" },
      { internalType: "uint256", name: "_amount", type: "uint256" },
    ],
    name: "unListSocialToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_id", type: "uint256" }],
    name: "unlistVideo",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
export const Token = [
  { inputs: [], stateMutability: "nonpayable", type: "constructor" },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "Id",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "string",
        name: "URI",
        type: "string",
      },
      {
        indexed: false,
        internalType: "address",
        name: "Advertiser",
        type: "address",
      },
    ],
    name: "AdCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "operator",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "approved",
        type: "bool",
      },
    ],
    name: "ApprovalForAll",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "Id",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "string",
        name: "URI",
        type: "string",
      },
      {
        indexed: false,
        internalType: "address",
        name: "Owner",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "displayCharge",
        type: "uint256",
      },
    ],
    name: "RoomMinted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "ID",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "string",
        name: "URI",
        type: "string",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "price",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "launched",
        type: "bool",
      },
      {
        indexed: false,
        internalType: "address",
        name: "creator",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "maxHoldingAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "videoIds",
        type: "uint256",
      },
    ],
    name: "TokenMinted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "operator",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256[]",
        name: "ids",
        type: "uint256[]",
      },
      {
        indexed: false,
        internalType: "uint256[]",
        name: "values",
        type: "uint256[]",
      },
    ],
    name: "TransferBatch",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "operator",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
    ],
    name: "TransferSingle",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "string",
        name: "value",
        type: "string",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
    ],
    name: "URI",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "Id",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "string",
        name: "URI",
        type: "string",
      },
      {
        indexed: false,
        internalType: "address",
        name: "Owner",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "roomId",
        type: "uint256",
      },
    ],
    name: "VideoMinted",
    type: "event",
  },
  {
    inputs: [
      { internalType: "address", name: "account", type: "address" },
      { internalType: "uint256", name: "id", type: "uint256" },
    ],
    name: "balanceOf",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address[]", name: "accounts", type: "address[]" },
      { internalType: "uint256[]", name: "ids", type: "uint256[]" },
    ],
    name: "balanceOfBatch",
    outputs: [{ internalType: "uint256[]", name: "", type: "uint256[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "_uri", type: "string" }],
    name: "createAd",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "_URI", type: "string" },
      {
        internalType: "uint256",
        name: "_displayCharge",
        type: "uint256",
      },
    ],
    name: "createRoom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_id", type: "uint256" }],
    name: "getAd",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "Id", type: "uint256" },
          { internalType: "string", name: "URI", type: "string" },
          {
            internalType: "address",
            name: "Advertiser",
            type: "address",
          },
          {
            internalType: "uint256[]",
            name: "PublishingRooms",
            type: "uint256[]",
          },
          { internalType: "bool", name: "Active", type: "bool" },
          {
            internalType: "uint256",
            name: "TotalSpent",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "CurrentBudget",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "MaxBudget",
            type: "uint256",
          },
        ],
        internalType: "struct Token.Ad",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_account", type: "address" },
      { internalType: "uint256", name: "_id", type: "uint256" },
    ],
    name: "getBalance",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getCreatorzTokens",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_id", type: "uint256" }],
    name: "getRoom",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "Id", type: "uint256" },
          { internalType: "string", name: "URI", type: "string" },
          { internalType: "address", name: "Creator", type: "address" },
          { internalType: "address", name: "Owner", type: "address" },
          { internalType: "uint256", name: "Price", type: "uint256" },
          {
            internalType: "uint256",
            name: "DisplayReward",
            type: "uint256",
          },
          {
            internalType: "uint256[]",
            name: "VideoIds",
            type: "uint256[]",
          },
          { internalType: "bool", name: "Listed", type: "bool" },
        ],
        internalType: "struct Token.Room",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_id", type: "uint256" }],
    name: "getSocialToken",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "ID", type: "uint256" },
          { internalType: "string", name: "URI", type: "string" },
          {
            internalType: "uint256",
            name: "totalSupply",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "circulatingSupply",
            type: "uint256",
          },
          { internalType: "uint256", name: "price", type: "uint256" },
          { internalType: "bool", name: "launched", type: "bool" },
          { internalType: "address", name: "creator", type: "address" },
          {
            internalType: "uint256",
            name: "maxHoldingAmount",
            type: "uint256",
          },
          { internalType: "uint256", name: "videoIds", type: "uint256" },
        ],
        internalType: "struct Token.SocialToken",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_id", type: "uint256" },
      { internalType: "address", name: "_account", type: "address" },
    ],
    name: "getSocialTokenHolder",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "Id", type: "uint256" },
          { internalType: "uint256", name: "amount", type: "uint256" },
          { internalType: "uint256", name: "price", type: "uint256" },
          {
            internalType: "uint256",
            name: "currentlyListed",
            type: "uint256",
          },
        ],
        internalType: "struct Token.SocialTokenHolder",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_id", type: "uint256" }],
    name: "getVideo",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "Id", type: "uint256" },
          { internalType: "string", name: "URI", type: "string" },
          { internalType: "address", name: "Owner", type: "address" },
          { internalType: "address", name: "Creator", type: "address" },
          { internalType: "uint256", name: "Price", type: "uint256" },
          {
            internalType: "uint256",
            name: "SocialTokenId",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "OwnerPercentage",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "HoldersPercentage",
            type: "uint256",
          },
          {
            internalType: "address[]",
            name: "Benefeciaries",
            type: "address[]",
          },
          { internalType: "bool", name: "Listed", type: "bool" },
          { internalType: "bool", name: "Published", type: "bool" },
          { internalType: "bool", name: "AdsEnabled", type: "bool" },
          { internalType: "uint256", name: "RoomId", type: "uint256" },
        ],
        internalType: "struct Token.Video",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "account", type: "address" },
      { internalType: "address", name: "operator", type: "address" },
    ],
    name: "isApprovedForAll",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_amount", type: "uint256" },
      { internalType: "uint256", name: "_price", type: "uint256" },
      { internalType: "string", name: "_URI", type: "string" },
      {
        internalType: "uint256",
        name: "_maxHoldingAmount",
        type: "uint256",
      },
      { internalType: "uint256", name: "_videoId", type: "uint256" },
    ],
    name: "mintSocialTokens",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "_URI", type: "string" },
      { internalType: "uint256", name: "_roomId", type: "uint256" },
    ],
    name: "mintVideo",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "from", type: "address" },
      { internalType: "address", name: "to", type: "address" },
      { internalType: "uint256[]", name: "ids", type: "uint256[]" },
      { internalType: "uint256[]", name: "amounts", type: "uint256[]" },
      { internalType: "bytes", name: "data", type: "bytes" },
    ],
    name: "safeBatchTransferFrom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "from", type: "address" },
      { internalType: "address", name: "to", type: "address" },
      { internalType: "uint256", name: "id", type: "uint256" },
      { internalType: "uint256", name: "amount", type: "uint256" },
      { internalType: "bytes", name: "data", type: "bytes" },
    ],
    name: "safeTransferFrom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "operator", type: "address" },
      { internalType: "bool", name: "approved", type: "bool" },
    ],
    name: "setApprovalForAll",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes4", name: "interfaceId", type: "bytes4" }],
    name: "supportsInterface",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_from", type: "address" },
      { internalType: "address", name: "_to", type: "address" },
      { internalType: "uint256[]", name: "_ids", type: "uint256[]" },
      { internalType: "uint256[]", name: "_amounts", type: "uint256[]" },
    ],
    name: "transferBatch",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_from", type: "address" },
      { internalType: "address", name: "_to", type: "address" },
      { internalType: "uint256", name: "_id", type: "uint256" },
      { internalType: "uint256", name: "_amount", type: "uint256" },
    ],
    name: "transferTokens",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_id", type: "uint256" },
      { internalType: "uint256", name: "_roomId", type: "uint256" },
      { internalType: "uint256", name: "roomAdded", type: "uint256" },
      { internalType: "bool", name: "_status", type: "bool" },
      { internalType: "uint256", name: "_totalSpent", type: "uint256" },
      {
        internalType: "uint256",
        name: "_currentBudget",
        type: "uint256",
      },
      { internalType: "uint256", name: "_maxBudget", type: "uint256" },
    ],
    name: "updateAdParameters",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_id", type: "uint256" },
      { internalType: "address", name: "_owner", type: "address" },
      { internalType: "uint256", name: "_price", type: "uint256" },
      {
        internalType: "uint256",
        name: "_displayCharge",
        type: "uint256",
      },
      { internalType: "uint256", name: "_videoId", type: "uint256" },
      { internalType: "uint256", name: "_action", type: "uint256" },
      { internalType: "bool", name: "_listed", type: "bool" },
    ],
    name: "updateRoomParameters",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_id", type: "uint256" },
      { internalType: "uint256", name: "_amount", type: "uint256" },
      { internalType: "uint256", name: "_price", type: "uint256" },
      {
        internalType: "uint256",
        name: "_currentlyListed",
        type: "uint256",
      },
      { internalType: "address", name: "_account", type: "address" },
    ],
    name: "updateSocialTokenHolderParameters",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_id", type: "uint256" },
      {
        internalType: "uint256",
        name: "_circulatingSupply",
        type: "uint256",
      },
      { internalType: "uint256", name: "price", type: "uint256" },
      { internalType: "bool", name: "_launched", type: "bool" },
      { internalType: "uint256", name: "videoId", type: "uint256" },
    ],
    name: "updateSocialTokenParameters",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_id", type: "uint256" },
      { internalType: "address", name: "_owner", type: "address" },
      { internalType: "uint256", name: "_price", type: "uint256" },
      { internalType: "address", name: "_beneficiary", type: "address" },
      { internalType: "uint256", name: "_action", type: "uint256" },
      { internalType: "bool", name: "_listed", type: "bool" },
      { internalType: "bool", name: "_published", type: "bool" },
      { internalType: "bool", name: "_AdsEnabled", type: "bool" },
      { internalType: "uint256", name: "_roomId", type: "uint256" },
    ],
    name: "updateVideoParameters",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_id", type: "uint256" },
      {
        internalType: "uint256",
        name: "_ownerPercentage",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_holderPercentage",
        type: "uint256",
      },
    ],
    name: "updateVideoRevenueParameters",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
    name: "uri",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
];
